# -*- coding: utf-8 -*-
"""suma.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K6R6YT4l19dESN9z1FaRFwViliYmtYcr
"""

# app.py
import streamlit as st

st.title("🔢 Sumador de dos números")

num1 = st.number_input("Escribe el primer número", value=0.0)
num2 = st.number_input("Escribe el segundo número", value=0.0)

if st.button("Sumar"):
    resultado = num1 + num2
    st.success(f"El resultado es: {resultado}")